import { afterEach,beforeEach,describe,expect,test } from "vitest";import type { ManagedCampaignRecord } from "@/lib/campaigns/types";import type { ContentVersionRecord } from "@/lib/content-workspace/types";import { createEmailCampaignItem,createEmailCampaignVersion,getEmailCampaignVersion,listEmailCampaignEvents,purgeEmailCampaignData,updateEmailCampaignVersion } from "@/lib/email-campaigns/repository";import { computeEmailStepClaimFindings,createSeededEmailCampaignInput,validateEmailCampaignInput } from "@/lib/email-campaigns/service";import type { EmailCampaignVersionInput } from "@/lib/email-campaigns/types";import { getInitiativeBySlug } from "@/lib/initiatives/repository";
const slug="keon-systems",context={campaignIds:new Set(["campaign-1"]),eligibleContentVersionIds:new Set(["content-1"]),brandVoiceGuidelineIds:new Set(["voice-1"])};
function content(overrides:Partial<ContentVersionRecord>={}):ContentVersionRecord{return{id:"content-1",contentItemId:"item-1",initiativeSlug:slug,versionNumber:1,title:"Governed execution proof",status:"approved",channel:"Email",format:"Sequence source",objective:"Show a reviewable execution path",audience:"Enterprise platform leaders",offer:"Proof walkthrough",cta:"Request a proof walkthrough",campaignId:"campaign-1",brandVoiceGuidelineId:"voice-1",brandVoiceSnapshot:"Approved voice snapshot",sourceMaterials:[{id:"source-1",sourceType:"manual-reference",label:"Proof brief",reference:"proof-v1",evidenceNote:"Operator-reviewed evidence."}],body:"Enterprise leaders can inspect how policy decisions precede effects and leave reviewable evidence.",authorship:"operator-authored",claimFindings:[],notes:"",createdAt:"2026-07-22T14:00:00.000Z",updatedAt:"2026-07-22T14:00:00.000Z",approvedAt:"2026-07-22T14:00:00.000Z",...overrides};}
function campaign():ManagedCampaignRecord{return{id:"campaign-1",initiativeSlug:slug,name:"Keon proof launch",status:"planning",goal:"Generate qualified proof walkthroughs",channel:"email",audience:"Enterprise platform leaders",primaryCta:"Request a proof walkthrough",currentFocus:"Proof",assetTypes:["email"],claimSensitivity:"high",launchReadiness:"planning",notes:"",createdAt:"2026-07-22T14:00:00.000Z",updatedAt:"2026-07-22T14:00:00.000Z"};}
function ready(input:EmailCampaignVersionInput):EmailCampaignVersionInput{return{...input,status:"review-ready",senderName:"Keon Systems",replyTo:"team@keon.systems",suppressionPlan:"Apply current unsubscribed, bounced, and do-not-contact records before delivery.",unsubscribePlan:"Provider footer must include a working unsubscribe mechanism.",senderAuthenticationPlan:"Verify SPF, DKIM, and DMARC with the selected provider.",physicalAddressPlan:"Confirm the authorized business mailing address in the provider footer."};}
beforeEach(()=>purgeEmailCampaignData(slug));afterEach(()=>purgeEmailCampaignData(slug));
describe("email marketing campaign builder",()=>{
test("seeds a deterministic three-email source-backed sequence",()=>{const input=createSeededEmailCampaignInput(content(),campaign());expect(input.steps).toHaveLength(3);expect(input.steps.map((step)=>step.order)).toEqual([1,2,3]);expect(input.steps[0].delayDays).toBe(0);expect(new Set(input.steps.map((step)=>step.sourceContentVersionId))).toEqual(new Set(["content-1"]));});
test("enforces same-initiative references, contiguous order, and bounded delays",()=>{const input=createSeededEmailCampaignInput(content(),campaign());expect(()=>validateEmailCampaignInput({...input,campaignId:"foreign"},context)).toThrow(/same initiative/i);expect(()=>validateEmailCampaignInput({...input,steps:input.steps.map((step,index)=>index===1?{...step,sourceContentVersionId:"foreign"}:step)},context)).toThrow(/same initiative/i);expect(()=>validateEmailCampaignInput({...input,steps:input.steps.map((step,index)=>index===1?{...step,order:4}:step)},context)).toThrow(/contiguous/i);expect(()=>validateEmailCampaignInput({...input,steps:input.steps.map((step,index)=>index===0?{...step,delayDays:1}:step)},context)).toThrow(/zero-day/i);});
test("requires sender, suppression, unsubscribe, authentication, and address planning before review",()=>{expect(()=>validateEmailCampaignInput({...createSeededEmailCampaignInput(content(),campaign()),status:"review-ready"},context)).toThrow(/sender name/i);expect(validateEmailCampaignInput(ready(createSeededEmailCampaignInput(content(),campaign())),context).status).toBe("review-ready");});
test("computes claim findings across subject, preheader, body, and CTA",()=>{const input=createSeededEmailCampaignInput(content(),campaign()),initiative=getInitiativeBySlug(slug)!;const findings=computeEmailStepClaimFindings(initiative,{...input.steps[0],subject:"Production Runtime enforcement"});expect(findings.map((item)=>item.handling)).toContain("needs-proof");expect(()=>validateEmailCampaignInput({...ready(input),status:"approved",steps:input.steps.map((step,index)=>index===0?{...step,claimFindings:findings}:step)},context)).toThrow(/claim findings/i);});
test("approves, preserves immutability, supersedes, and records evidence",()=>{const draft=validateEmailCampaignInput(createSeededEmailCampaignInput(content(),campaign()),context),first=createEmailCampaignItem(slug,draft),review=validateEmailCampaignInput(ready(draft),context);updateEmailCampaignVersion(first.id,review);updateEmailCampaignVersion(first.id,{...review,status:"approved"});expect(()=>updateEmailCampaignVersion(first.id,{...review,status:"approved",notes:"mutated"})).toThrow(/immutable/i);const second=createEmailCampaignVersion(first.id,draft);updateEmailCampaignVersion(second.id,review);updateEmailCampaignVersion(second.id,{...review,status:"approved"});expect(getEmailCampaignVersion(first.id)?.status).toBe("superseded");expect(getEmailCampaignVersion(second.id)?.status).toBe("approved");expect(listEmailCampaignEvents(first.id).some((event)=>event.eventType==="email-campaign.version-superseded")).toBe(true);});
});
