import { beforeEach,describe,expect,test } from "vitest";
import type { ContentVersionRecord } from "@/lib/content-workspace/types";
import { getInitiativeBySlug } from "@/lib/initiatives/repository";
import { createVideoScriptItem,createVideoScriptVersion,getVideoScriptVersion,listVideoScriptEvents,purgeVideoScriptData,updateVideoScriptVersion } from "@/lib/video-scripts/repository";
import { computeVideoScriptClaimFindings,createSeededVideoScriptInput,validateVideoScriptInput } from "@/lib/video-scripts/service";

const slug="keon-systems";
const context={initiativeSlug:slug,eligibleContentVersionIds:new Set(["content-1"]),campaignIds:new Set(["campaign-1"]),brandVoiceGuidelineIds:new Set(["voice-1"])};
function content(overrides:Partial<ContentVersionRecord>={}):ContentVersionRecord{return {id:"content-1",contentItemId:"item-1",initiativeSlug:slug,versionNumber:1,title:"Governed execution proof",status:"approved",channel:"LinkedIn",format:"Founder post",objective:"Show enterprise leaders a reviewable execution path",audience:"Enterprise platform and security leaders",offer:"Proof walkthrough",cta:"Request a proof walkthrough",campaignId:"campaign-1",brandVoiceGuidelineId:"voice-1",brandVoiceSnapshot:"Approved voice snapshot",sourceMaterials:[{id:"source-1",sourceType:"manual-reference",label:"Proof brief",reference:"proof-v1",evidenceNote:"Operator-reviewed evidence."}],body:"Enterprise leaders can inspect how policy decisions precede effects and leave reviewable evidence.",authorship:"operator-authored",claimFindings:[],notes:"",createdAt:"2026-07-22T14:00:00.000Z",updatedAt:"2026-07-22T14:00:00.000Z",approvedAt:"2026-07-22T14:00:00.000Z",...overrides};}
beforeEach(()=>purgeVideoScriptData(slug));
describe("short-form video scripts",()=>{
  test("seeds a deterministic, contiguous 30-second scene plan",()=>{const input=createSeededVideoScriptInput(content());expect(input.scenes).toHaveLength(4);expect(input.scenes[0].startSecond).toBe(0);expect(input.scenes.at(-1)?.endSecond).toBe(30);expect(input.scenes.every((scene,index)=>index===0||scene.startSecond===input.scenes[index-1].endSecond)).toBe(true);expect(input.sourceMaterials).toHaveLength(1);});
  test("enforces same-initiative source, campaign, voice, and complete timing",()=>{const input=createSeededVideoScriptInput(content());expect(()=>validateVideoScriptInput({...input,sourceContentVersionId:"foreign"},context)).toThrow(/same initiative/i);expect(()=>validateVideoScriptInput({...input,campaignId:"foreign"},context)).toThrow(/same initiative/i);expect(()=>validateVideoScriptInput({...input,brandVoiceGuidelineId:"foreign"},context)).toThrow(/same initiative/i);expect(()=>validateVideoScriptInput({...input,scenes:input.scenes.map((scene,index)=>index===1?{...scene,startSecond:scene.startSecond+1}:scene)},context)).toThrow(/contiguous/i);});
  test("recomputes initiative claim findings across narration and screen text",()=>{const initiative=getInitiativeBySlug(slug)!;const input=createSeededVideoScriptInput(content());input.scenes[0].narration="Production Runtime enforcement";expect(computeVideoScriptClaimFindings(initiative,input).map((item)=>item.handling)).toContain("needs-proof");});
  test("requires complete scene evidence before review",()=>{const input=createSeededVideoScriptInput(content());input.status="review-ready";input.scenes[0].evidenceNote="";expect(()=>validateVideoScriptInput(input,context)).toThrow(/evidence note/i);});
  test("approves, preserves immutability, supersedes, and records events",()=>{const initial=validateVideoScriptInput(createSeededVideoScriptInput(content()),context);const first=createVideoScriptItem(slug,initial);const review=validateVideoScriptInput({...initial,status:"review-ready"},context);updateVideoScriptVersion(first.id,review);updateVideoScriptVersion(first.id,{...review,status:"approved"});expect(()=>updateVideoScriptVersion(first.id,{...review,status:"approved",notes:"mutated"})).toThrow(/immutable/i);const second=createVideoScriptVersion(first.id,{...initial,origin:"operator-edited"});updateVideoScriptVersion(second.id,review);updateVideoScriptVersion(second.id,{...review,status:"approved"});expect(getVideoScriptVersion(first.id)?.status).toBe("superseded");expect(getVideoScriptVersion(second.id)?.status).toBe("approved");expect(listVideoScriptEvents(first.id).some((event)=>event.eventType==="video-script.version-superseded")).toBe(true);});
});
