"use client";

import { AlertTriangle, Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";
import { createContentItemAction, createContentVersionAction, generateContentDraftAction, saveContentVersionAction } from "@/app/actions/content-workspace";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { BrandVoiceVersionSummary } from "@/lib/brand-voice/types";
import { contentAuthorshipOptions, type ContentCampaignOption, type ContentEvent, type ContentGenerationRun, type ContentSourceOption, type ContentStatus, type ContentVersionInput, type ContentVersionRecord } from "@/lib/content-workspace/types";

type Props = { initiativeSlug: string; initiativeName: string; versions: ContentVersionRecord[]; selected?: ContentVersionRecord; brandVoices: BrandVoiceVersionSummary[]; campaigns: ContentCampaignOption[]; sourceOptions: ContentSourceOption[]; generationRuns: ContentGenerationRun[]; events: ContentEvent[] };
const inputClass = "w-full rounded-lg border border-border bg-background px-3 py-2 text-sm";
const areaClass = `${inputClass} min-h-28`;

function inputOf(record: ContentVersionRecord): ContentVersionInput { return { title: record.title, status: record.status, channel: record.channel, format: record.format, objective: record.objective, audience: record.audience, offer: record.offer, cta: record.cta, campaignId: record.campaignId, brandVoiceGuidelineId: record.brandVoiceGuidelineId, brandVoiceSnapshot: record.brandVoiceSnapshot, sourceMaterials: record.sourceMaterials, body: record.body, authorship: record.authorship, claimFindings: record.claimFindings, notes: record.notes }; }
function statuses(status: ContentStatus): ContentStatus[] { if (status === "draft") return ["draft", "review-ready"]; if (status === "review-ready") return ["review-ready", "draft", "changes-requested", "approved"]; if (status === "changes-requested") return ["changes-requested", "draft", "review-ready"]; return [status]; }

export function ContentWorkspace(props: Props) {
  const router = useRouter(); const [isPending, startTransition] = useTransition();
  const [newTitle, setNewTitle] = useState(""); const [form, setForm] = useState<ContentVersionInput | undefined>(() => props.selected ? inputOf(props.selected) : undefined);
  const [urls, setUrls] = useState(() => props.selected?.sourceMaterials.filter((source) => source.sourceType === "url").map((source) => source.reference).join("\n") ?? "");
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const readOnly = !props.selected || ["approved", "superseded"].includes(props.selected.status);
  const itemVersions = props.selected ? props.versions.filter((version) => version.contentItemId === props.selected?.contentItemId) : [];
  const selectedLibraryIds = useMemo(() => new Set(form?.sourceMaterials.filter((source) => source.sourceType === "library-entry").map((source) => source.reference)), [form]);
  const update = <K extends keyof ContentVersionInput>(key: K, value: ContentVersionInput[K]) => setForm((current) => current ? { ...current, [key]: value } : current);

  const run = (work: () => Promise<ContentVersionRecord>, success: string) => { setError(null); setMessage(null); startTransition(async () => { try { const result = await work(); setForm(inputOf(result)); setMessage(success); router.push(`/initiatives/${props.initiativeSlug}/content?version=${result.id}`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Content operation failed."); } }); };
  const createItem = () => run(() => createContentItemAction(props.initiativeSlug, newTitle), "Content item created.");
  const sourcePayload = () => form ? [...form.sourceMaterials.filter((source) => source.sourceType !== "url"), ...urls.split("\n").map((url) => url.trim()).filter(Boolean).map((url, index) => ({ id: `url-${index + 1}`, sourceType: "url" as const, label: `External reference ${index + 1}`, reference: url, evidenceNote: "Operator-supplied provenance reference; MarketOps did not fetch this URL." }))] : [];
  const payload = () => ({ ...form!, sourceMaterials: sourcePayload() });
  const toggleSource = (source: ContentSourceOption) => { if (!form) return; const exists = selectedLibraryIds.has(source.id); update("sourceMaterials", exists ? form.sourceMaterials.filter((item) => !(item.sourceType === "library-entry" && item.reference === source.id)) : [...form.sourceMaterials, { id: `library-${source.id}`, sourceType: "library-entry", label: source.title, reference: source.id, evidenceNote: "Eligible initiative Library entry selected by the operator." }]); };

  return <div className="space-y-6">
    <Card><CardHeader><CardTitle>Content items</CardTitle><CardDescription>Create a source-backed draft or open an existing version.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><input className={`${inputClass} max-w-sm`} value={newTitle} onChange={(event) => setNewTitle(event.target.value)} placeholder="New content title"/><Button type="button" disabled={isPending || !newTitle.trim()} onClick={createItem}><Plus className="mr-1 size-4"/>Create content</Button></div><div className="flex flex-wrap gap-2">{props.versions.map((version) => <a key={version.id} href={`?version=${version.id}`} className={buttonVariants({ size: "sm", variant: version.id === props.selected?.id ? "default" : "outline" })}>{version.title} · v{version.versionNumber} · {version.status}</a>)}</div></CardContent></Card>
    {form && props.selected ? <>
      <Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>{form.title} · v{props.selected.versionNumber}</CardTitle><CardDescription>Approved versions are immutable; create a new version for revisions.</CardDescription></div><div className="flex flex-wrap gap-2"><a href={`/initiatives/${props.initiativeSlug}/persuasion?contentVersion=${props.selected.id}`} className={buttonVariants({ variant: "outline" })}>Persuasion review</a><Button type="button" variant="outline" disabled={isPending} onClick={() => run(() => createContentVersionAction(props.selected!.id), "New draft version created.")}>Create new version</Button></div></CardHeader><CardContent className="flex flex-wrap gap-2">{itemVersions.map((version) => <a key={version.id} href={`?version=${version.id}`} className={buttonVariants({ size: "sm", variant: version.id === props.selected?.id ? "default" : "outline" })}>v{version.versionNumber} · {version.status}</a>)}</CardContent></Card>
      <form className="space-y-6" onSubmit={(event) => { event.preventDefault(); run(() => saveContentVersionAction(props.selected!.id, payload()), "Content version saved. No publishing action occurred."); }}>
        <Section title="Brief and ownership" description="Define the intended content before drafting."><Field label="Title" value={form.title} disabled={readOnly} onChange={(v) => update("title", v)}/><Select label="Status" value={form.status} disabled={readOnly} options={statuses(props.selected.status)} onChange={(v) => update("status", v as ContentStatus)}/><Field label="Channel" value={form.channel} disabled={readOnly} onChange={(v) => update("channel", v)}/><Field label="Format" value={form.format} disabled={readOnly} onChange={(v) => update("format", v)}/><Area label="Objective" value={form.objective} disabled={readOnly} onChange={(v) => update("objective", v)}/><Area label="Audience" value={form.audience} disabled={readOnly} onChange={(v) => update("audience", v)}/><Field label="Offer" value={form.offer} disabled={readOnly} onChange={(v) => update("offer", v)}/><Field label="CTA" value={form.cta} disabled={readOnly} onChange={(v) => update("cta", v)}/><Select label="Campaign" value={form.campaignId} disabled={readOnly} options={["", ...props.campaigns.map((campaign) => campaign.id)]} labels={Object.fromEntries(props.campaigns.map((campaign) => [campaign.id, campaign.name]))} onChange={(v) => update("campaignId", v)}/><Select label="Authorship" value={form.authorship} disabled={readOnly} options={contentAuthorshipOptions} onChange={(v) => update("authorship", v as ContentVersionInput["authorship"])}/></Section>
        <Section title="Brand voice and provenance" description="Review requires a same-initiative approved voice and at least one source."><Select label="Approved brand voice" value={form.brandVoiceGuidelineId} disabled={readOnly} options={["", ...props.brandVoices.map((voice) => voice.id)]} labels={Object.fromEntries(props.brandVoices.map((voice) => [voice.id, `${voice.name} v${voice.versionNumber} · ${voice.status}`]))} onChange={(v) => update("brandVoiceGuidelineId", v)}/><Area label="URL references (one per line; stored only, never fetched)" value={urls} disabled={readOnly} onChange={setUrls}/><div className="md:col-span-2 space-y-2"><p className="text-sm font-medium">Eligible Library sources</p><div className="grid gap-2 md:grid-cols-2">{props.sourceOptions.map((source) => <label key={source.id} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" disabled={readOnly} checked={selectedLibraryIds.has(source.id)} onChange={() => toggleSource(source)}/><span>{source.title} <span className="text-muted-foreground">· {source.status}</span></span></label>)}</div></div></Section>
        <Section title="Draft" description="Generation creates a recorded suggestion; it never publishes or distributes content."><div className="md:col-span-2"><Area label="Content body" value={form.body} disabled={readOnly} onChange={(v) => { update("body", v); if (form.authorship === "ai-generated") update("authorship", "ai-assisted"); }}/></div><div className="md:col-span-2 flex flex-wrap gap-2">{!readOnly ? <><Button type="submit" disabled={isPending}>{isPending ? "Working..." : "Save content"}</Button><Button type="button" variant="outline" disabled={isPending} onClick={() => { setError(null); setMessage(null); startTransition(async () => { try { const result = await generateContentDraftAction(props.selected!.id, payload()); setForm(inputOf(result.version)); setMessage(`Generation ${result.run.status}. No publishing action occurred.`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Generation failed."); } }); }}>Generate suggestion</Button></> : <Badge variant="outline">Immutable version</Badge>}</div></Section>
        {form.claimFindings.length ? <Card className="border-amber-400/60"><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="size-4"/>Claim review required</CardTitle><CardDescription>Remove or substantiate these literal matches before approval.</CardDescription></CardHeader><CardContent className="space-y-2">{form.claimFindings.map((finding) => <div key={finding.id} className="rounded-lg border p-3 text-sm"><Badge variant="outline">{finding.handling}</Badge><p className="mt-2 font-medium">{finding.statement}</p><p className="text-muted-foreground">{finding.rationale} · {finding.origin}</p></div>)}</CardContent></Card> : null}
        <Area label="Internal notes" value={form.notes} disabled={readOnly} onChange={(v) => update("notes", v)}/>
        {error ? <p role="alert" className="rounded-lg border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}{message ? <p role="status" className="rounded-lg border border-emerald-500/40 p-3 text-sm">{message}</p> : null}
      </form>
      <Card><CardHeader><CardTitle>Generation and event evidence</CardTitle><CardDescription>Provider outcomes and version changes; no send or publish events exist.</CardDescription></CardHeader><CardContent className="space-y-3">{props.generationRuns.map((run) => <div key={run.id} className="rounded-lg border p-3 text-sm"><b>{run.status}</b> · {run.provider}/{run.model}<p className="text-muted-foreground">{run.requestSummary}{run.errorMessage ? ` · ${run.errorMessage}` : ""}</p></div>)}{props.events.map((event) => <div key={event.id} className="rounded-lg border p-3 text-sm"><b>{event.summary}</b><p className="text-muted-foreground">{event.eventType} · {formatTime(event.recordedAt)}</p></div>)}</CardContent></Card>
    </> : null}
    {!form && error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}
  </div>;
}

function formatTime(value: string) { return `${new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value))} UTC`; }
function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{children}</CardContent></Card>; }
function Field({ label, value, onChange, disabled=false }: { label:string; value:string; onChange:(v:string)=>void; disabled?:boolean }) { return <label className="space-y-2 text-sm"><span className="font-medium">{label}</span><input className={inputClass} value={value} disabled={disabled} onChange={(e)=>onChange(e.target.value)}/></label>; }
function Area({ label, value, onChange, disabled=false }: { label:string; value:string; onChange:(v:string)=>void; disabled?:boolean }) { return <label className="space-y-2 text-sm"><span className="font-medium">{label}</span><textarea className={areaClass} value={value} disabled={disabled} onChange={(e)=>onChange(e.target.value)}/></label>; }
function Select({ label, value, options, onChange, disabled=false, labels={} }: { label:string; value:string; options:readonly string[]; onChange:(v:string)=>void; disabled?:boolean; labels?:Record<string,string> }) { return <label className="space-y-2 text-sm"><span className="font-medium">{label}</span><select className={inputClass} value={value} disabled={disabled} onChange={(e)=>onChange(e.target.value)}>{options.map((option)=><option key={option} value={option}>{labels[option] ?? (option || "None")}</option>)}</select></label>; }
