"use client";
import { AlertTriangle,Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState,useTransition } from "react";
import { createVideoScriptAction,createVideoScriptVersionAction,saveVideoScriptVersionAction } from "@/app/actions/video-scripts";
import { Badge } from "@/components/ui/badge";
import { Button,buttonVariants } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { videoAspectRatioOptions,videoDurationOptions,videoPlatformOptions,type VideoScriptScene,type VideoScriptVersionInput,type VideoScriptVersionRecord } from "@/lib/video-scripts/types";
type ContentOption={id:string;title:string;versionNumber:number;status:string};
type Props={initiativeSlug:string;versions:VideoScriptVersionRecord[];selected?:VideoScriptVersionRecord;contentOptions:ContentOption[];events:Array<{id:string;eventType:string;summary:string;recordedAt:string}>};
const inputClass="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm",areaClass=`${inputClass} min-h-24`;
function inputOf(v:VideoScriptVersionRecord):VideoScriptVersionInput{return {title:v.title,status:v.status,platform:v.platform,aspectRatio:v.aspectRatio,durationSeconds:v.durationSeconds,objective:v.objective,audience:v.audience,campaignId:v.campaignId,sourceContentVersionId:v.sourceContentVersionId,sourceContentUpdatedAt:v.sourceContentUpdatedAt,sourceContentTitle:v.sourceContentTitle,sourceContentBody:v.sourceContentBody,sourceMaterials:v.sourceMaterials,brandVoiceGuidelineId:v.brandVoiceGuidelineId,brandVoiceSnapshot:v.brandVoiceSnapshot,scenes:v.scenes,caption:v.caption,cta:v.cta,claimFindings:v.claimFindings,origin:v.origin,notes:v.notes};}
function statuses(s:VideoScriptVersionInput["status"]){if(s==="draft")return["draft","review-ready"];if(s==="review-ready")return["review-ready","draft","changes-requested","approved"];if(s==="changes-requested")return["changes-requested","draft","review-ready"];return[s];}
export function VideoScriptWorkspace(props:Props){ const router=useRouter(),[pending,start]=useTransition(); const [source,setSource]=useState(props.contentOptions[0]?.id??""); const [form,setForm]=useState<VideoScriptVersionInput|undefined>(()=>props.selected?inputOf(props.selected):undefined); const [error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null); const readOnly=!props.selected||["approved","superseded"].includes(props.selected.status); const update=<K extends keyof VideoScriptVersionInput>(key:K,value:VideoScriptVersionInput[K])=>setForm((current)=>current?{...current,[key]:value}:current); const run=(work:()=>Promise<VideoScriptVersionRecord>,success:string)=>{setError(null);setMessage(null);start(async()=>{try{const result=await work();setForm(inputOf(result));setMessage(success);router.push(`/initiatives/${props.initiativeSlug}/video-scripts?version=${result.id}`);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Video script operation failed.");}});}; const scene=(index:number,key:keyof VideoScriptScene,value:string|number)=>update("scenes",form!.scenes.map((item,i)=>i===index?{...item,[key]:value}:item)); return <div className="space-y-6">
  <Card><CardHeader><CardTitle>Create from approved content</CardTitle><CardDescription>Deterministically seeds an editable plan; no media or provider request occurs.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><select className={`${inputClass} max-w-xl`} value={source} onChange={(e)=>setSource(e.target.value)}>{props.contentOptions.map((item)=><option key={item.id} value={item.id}>{item.title} · v{item.versionNumber} · {item.status}</option>)}</select><Button disabled={pending||!source} onClick={()=>run(()=>createVideoScriptAction(source),"Video script draft created. No media was generated.")}><Plus className="mr-1 size-4"/>Seed script</Button></CardContent></Card>
  <div className="flex flex-wrap gap-2">{props.versions.map((v)=><a key={v.id} href={`?version=${v.id}`} className={buttonVariants({size:"sm",variant:v.id===props.selected?.id?"default":"outline"})}>{v.title} · v{v.versionNumber} · {v.status}</a>)}</div>
  {form&&props.selected?<><Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>{form.title} · v{props.selected.versionNumber}</CardTitle><CardDescription>Source: {form.sourceContentTitle}. Approved versions are immutable.</CardDescription></div><Button variant="outline" disabled={pending} onClick={()=>run(()=>createVideoScriptVersionAction(props.selected!.id),"Editable script version created.")}>Create new version</Button></CardHeader></Card>
  <form className="space-y-6" onSubmit={(e)=>{e.preventDefault();run(()=>saveVideoScriptVersionAction(props.selected!.id,form),"Script saved. No rendering or publishing occurred.");}}><Card><CardHeader><CardTitle>Script brief</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Title" value={form.title} disabled={readOnly} onChange={(v)=>update("title",v)}/><Select label="Status" value={form.status} options={statuses(props.selected.status)} disabled={readOnly} onChange={(v)=>update("status",v as VideoScriptVersionInput["status"])}/><Select label="Platform" value={form.platform} options={videoPlatformOptions} disabled={readOnly} onChange={(v)=>update("platform",v as VideoScriptVersionInput["platform"])}/><Select label="Aspect ratio" value={form.aspectRatio} options={videoAspectRatioOptions} disabled={readOnly} onChange={(v)=>update("aspectRatio",v as VideoScriptVersionInput["aspectRatio"])}/><Select label="Duration" value={String(form.durationSeconds)} options={videoDurationOptions.map(String)} disabled={readOnly} onChange={(v)=>update("durationSeconds",Number(v))}/><Area label="Objective" value={form.objective} disabled={readOnly} onChange={(v)=>update("objective",v)}/><Area label="Audience" value={form.audience} disabled={readOnly} onChange={(v)=>update("audience",v)}/><Field label="CTA" value={form.cta} disabled={readOnly} onChange={(v)=>update("cta",v)}/><div className="md:col-span-2"><Area label="Caption" value={form.caption} disabled={readOnly} onChange={(v)=>update("caption",v)}/></div></CardContent></Card>
  <div className="space-y-4">{form.scenes.map((item,index)=><Card key={item.id}><CardHeader><CardTitle className="text-base">Scene {index+1} · {item.startSecond}-{item.endSecond}s</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Start second" value={String(item.startSecond)} disabled={readOnly} onChange={(v)=>scene(index,"startSecond",Number(v))}/><Field label="End second" value={String(item.endSecond)} disabled={readOnly} onChange={(v)=>scene(index,"endSecond",Number(v))}/><Area label="Narration" value={item.narration} disabled={readOnly} onChange={(v)=>scene(index,"narration",v)}/><Area label="On-screen text" value={item.onScreenText} disabled={readOnly} onChange={(v)=>scene(index,"onScreenText",v)}/><Area label="Visual direction" value={item.visualDirection} disabled={readOnly} onChange={(v)=>scene(index,"visualDirection",v)}/><Area label="Evidence note" value={item.evidenceNote} disabled={readOnly} onChange={(v)=>scene(index,"evidenceNote",v)}/></CardContent></Card>)}</div>
  {form.claimFindings.length?<Card className="border-amber-400/60"><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="size-4"/>Claim review required</CardTitle></CardHeader><CardContent>{form.claimFindings.map((f)=><p key={f.id} className="text-sm"><b>{f.statement}</b> · {f.rationale}</p>)}</CardContent></Card>:null}<Area label="Internal notes" value={form.notes} disabled={readOnly} onChange={(v)=>update("notes",v)}/>{!readOnly?<Button type="submit" disabled={pending}>{pending?"Working...":"Save script"}</Button>:<Badge variant="outline">Immutable version</Badge>}</form>
  <Card><CardHeader><CardTitle>Evidence</CardTitle></CardHeader><CardContent className="space-y-2">{props.events.map((e)=><div key={e.id} className="rounded-lg border p-3 text-sm"><b>{e.summary}</b><p className="text-muted-foreground">{e.eventType} · {e.recordedAt}</p></div>)}</CardContent></Card></>:null}{error?<p role="alert" className="text-sm text-destructive">{error}</p>:null}{message?<p role="status" className="text-sm">{message}</p>:null}</div>; }
function Field({label,value,onChange,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;disabled?:boolean}){return <label className="space-y-2 text-sm"><span className="font-medium">{label}</span><input className={inputClass} value={value} disabled={disabled} onChange={(e)=>onChange(e.target.value)}/></label>;} function Area({label,value,onChange,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;disabled?:boolean}){return <label className="space-y-2 text-sm"><span className="font-medium">{label}</span><textarea className={areaClass} value={value} disabled={disabled} onChange={(e)=>onChange(e.target.value)}/></label>;} function Select({label,value,options,onChange,disabled=false}:{label:string;value:string;options:readonly string[];onChange:(v:string)=>void;disabled?:boolean}){return <label className="space-y-2 text-sm"><span className="font-medium">{label}</span><select className={inputClass} value={value} disabled={disabled} onChange={(e)=>onChange(e.target.value)}>{options.map((v)=><option key={v}>{v}</option>)}</select></label>;}
