import type { ChecklistDefinition } from "@/lib/readiness/types";

export const readinessCategoryLabels = {
  foundation: "Foundation",
  trust: "Trust",
  measurement: "Measurement",
  operations: "Operations",
  distribution: "Distribution",
} as const;

export const readinessDefinitions: ChecklistDefinition[] = [
  {
    id: "baseline-positioning-approved",
    label: "Positioning is approved",
    description: "The current positioning is stable enough to support launch traffic.",
    level: "required",
    category: "foundation",
    active: true,
    displayOrder: 10,
  },
  {
    id: "baseline-primary-cta-live",
    label: "Primary CTA is live",
    description: "The initiative has a working primary CTA on the live site.",
    level: "required",
    category: "foundation",
    active: true,
    displayOrder: 20,
  },
  {
    id: "baseline-traffic-measurement-ready",
    label: "Traffic measurement is ready",
    description: "Basic launch measurement is in place before campaigns start.",
    level: "recommended",
    category: "measurement",
    active: true,
    displayOrder: 30,
  },
  {
    id: "baseline-launch-operator-assigned",
    label: "Launch operator is assigned",
    description: "An operator owns launch-day monitoring and response.",
    level: "recommended",
    category: "operations",
    active: true,
    displayOrder: 40,
  },
  {
    id: "baseline-distribution-plan-tracked",
    label: "Distribution plan is tracked",
    description: "The intended launch surfaces are identified and tracked.",
    level: "informational",
    category: "distribution",
    active: true,
    displayOrder: 50,
  },
  {
    id: "keon-proof-surface-reviewed",
    label: "Proof surface is reviewed",
    description: "The public proof and access-building surface is reviewed before launch.",
    level: "required",
    category: "trust",
    active: true,
    displayOrder: 60,
    initiativeSlugs: ["keon-systems"],
  },
  {
    id: "biostack-observational-language-reviewed",
    label: "Observational language is reviewed",
    description: "Launch copy stays within observational supplement tracking boundaries.",
    level: "required",
    category: "trust",
    active: true,
    displayOrder: 70,
    initiativeSlugs: ["biostack"],
  },
  {
    id: "silentapply-waitlist-path-checked",
    label: "Waitlist path is checked",
    description: "The waitlist capture path is ready before outreach begins.",
    level: "required",
    category: "operations",
    active: true,
    displayOrder: 80,
    initiativeSlugs: ["silentapply"],
  },
  {
    id: "forgepilot-build-status-surface-checked",
    label: "Build status surface is checked",
    description: "The build-progress surface is ready to receive attention from launch traffic.",
    level: "recommended",
    category: "foundation",
    active: true,
    displayOrder: 90,
    initiativeSlugs: ["forgepilot"],
  },
];
