export const managedCampaignSeed = [
  {
    id: "keon-proof-push",
    initiativeSlug: "keon-systems",
    name: "Governed AI Execution Proof Push",
    status: "active",
    goal: "Drive qualified access requests from security, platform, and governance leaders.",
    channel: "website / founder-led / proof content",
    audience: "CISOs, CTOs, platform engineering, regulated enterprise",
    primaryCta: "Request access",
    currentFocus: "Proof-led access building",
    assetTypes: ["proof tour", "access page", "founder post", "executive brief"],
    claimSensitivity: "high",
    launchReadiness: "in-progress",
    notes: "Must stay verifier-bound and avoid proof overclaims.",
  },
  {
    id: "biostack-alpha-push",
    initiativeSlug: "biostack",
    name: "Alpha Trust and Provider Summary Push",
    status: "active",
    goal: "Increase saved protocol usage and provider-summary engagement.",
    channel: "product-led / educational content",
    audience: "Self-optimizers, providers, wellness operators",
    primaryCta: "Track a protocol",
    currentFocus: "Conversion polish",
    assetTypes: ["product page", "provider summary", "onboarding copy", "founder post"],
    claimSensitivity: "high",
    launchReadiness: "in-progress",
    notes: "Must remain observational and avoid medical claims.",
  },
  {
    id: "silentapply-waitlist",
    initiativeSlug: "silentapply",
    name: "Waitlist Validation Campaign",
    status: "planning",
    goal: "Validate demand for targeted application workflow automation.",
    channel: "waitlist / founder-led / social",
    audience: "Job seekers, career switchers, laid-off tech workers",
    primaryCta: "Join waitlist",
    currentFocus: "Positioning refinement",
    assetTypes: ["landing page", "waitlist copy", "social post", "user interview prompt"],
    claimSensitivity: "medium",
    launchReadiness: "planning",
    notes: "Must avoid guaranteed interview or job outcome claims.",
  },
  {
    id: "forgepilot-narrative-test",
    initiativeSlug: "forgepilot",
    name: "Builder Workflow Narrative Test",
    status: "planning",
    goal: "Test positioning around product workflow clarity and launch readiness.",
    channel: "founder-led / build-in-public",
    audience: "Indie hackers, technical founders, product builders",
    primaryCta: "Follow build progress",
    currentFocus: "Positioning refinement",
    assetTypes: ["founder post", "landing page section", "product brief"],
    claimSensitivity: "medium",
    launchReadiness: "planning",
    notes: "Must avoid autonomous shipping or guaranteed PMF claims.",
  },
] as const;
