"use server";
import { requireSessionTenant } from "@/lib/auth/session";
import { revalidatePath } from "next/cache";
import { getBrandVoiceGuideline, requireRowTenantMatch as requireBrandVoiceRowTenant } from "@/lib/brand-voice/repository";
import { getManagedCampaignById, requireRowTenantMatch as requireCampaignRowTenant } from "@/lib/campaigns/repository";
import { getContentVersion, requireRowTenantMatch as requireContentRowTenant } from "@/lib/content-workspace/repository";
import { createEmailCampaignItem,createEmailCampaignVersion,getEmailCampaignVersion,updateEmailCampaignVersion,requireRowTenantMatch as requireEmailRowTenant } from "@/lib/email-campaigns/repository";
import { computeEmailStepClaimFindings,createSeededEmailCampaignInput,validateEmailCampaignInput } from "@/lib/email-campaigns/service";
import type { EmailCampaignVersionInput } from "@/lib/email-campaigns/types";
import { getInitiativeBySlug, requireRowTenantMatch as requireInitiativeRowTenant } from "@/lib/initiatives/repository";

function path(slug:string){revalidatePath(`/initiatives/${slug}`);revalidatePath(`/initiatives/${slug}/email-campaigns`);}
function canonicalize(slug:string,input:EmailCampaignVersionInput,tenantCtx?:{sessionTenant:string;action:string}){const initiative=getInitiativeBySlug(slug);if(!initiative)throw new Error("Initiative not found.");if(tenantCtx)requireInitiativeRowTenant(tenantCtx.sessionTenant,initiative,tenantCtx.action);const campaign=getManagedCampaignById(input.campaignId);if(!campaign||campaign.initiativeSlug!==slug)throw new Error("Campaign must belong to the same initiative.");if(tenantCtx)requireCampaignRowTenant(tenantCtx.sessionTenant,campaign,tenantCtx.action);const eligible=new Set<string>(),voices=new Set<string>();const steps=input.steps.map((step)=>{const source=getContentVersion(step.sourceContentVersionId);if(!source||source.initiativeSlug!==slug||!["approved","superseded"].includes(source.status))throw new Error("Source content must be approved or superseded in the same initiative.");if(tenantCtx)requireContentRowTenant(tenantCtx.sessionTenant,source,tenantCtx.action);const voice=getBrandVoiceGuideline(source.brandVoiceGuidelineId);if(!voice||voice.initiativeSlug!==slug||!["approved","superseded"].includes(voice.status))throw new Error("Pinned brand voice must be approved or superseded in the same initiative.");if(tenantCtx)requireBrandVoiceRowTenant(tenantCtx.sessionTenant,voice,tenantCtx.action);eligible.add(source.id);voices.add(voice.id);const canonical={...step,sourceContentUpdatedAt:source.updatedAt,sourceContentTitle:source.title,sourceMaterials:source.sourceMaterials,brandVoiceGuidelineId:voice.id,brandVoiceSnapshot:source.brandVoiceSnapshot};return{...canonical,claimFindings:computeEmailStepClaimFindings(initiative,canonical,voice)};});return validateEmailCampaignInput({...input,campaignName:campaign.name,steps},{campaignIds:new Set([campaign.id]),eligibleContentVersionIds:eligible,brandVoiceGuidelineIds:voices});}
export async function createEmailCampaignAction(slug:string,sourceId:string,campaignId:string){ const sessionTenant=await requireSessionTenant({action:"create email campaign"}); const tenantCtx={sessionTenant,action:"create email campaign"}; const source=getContentVersion(sourceId),campaign=getManagedCampaignById(campaignId);if(!source||source.initiativeSlug!==slug||!["approved","superseded"].includes(source.status))throw new Error("Select approved or superseded source content from this initiative.");requireContentRowTenant(sessionTenant,source,"create email campaign");if(!campaign||campaign.initiativeSlug!==slug)throw new Error("Select a campaign from this initiative.");requireCampaignRowTenant(sessionTenant,campaign,"create email campaign");const record=createEmailCampaignItem(slug,canonicalize(slug,createSeededEmailCampaignInput(source,campaign),tenantCtx));path(slug);return record;}
export async function createEmailCampaignVersionAction(baseId:string){ const sessionTenant=await requireSessionTenant({action:"create email campaign version"}); const tenantCtx={sessionTenant,action:"create email campaign version"}; const base=getEmailCampaignVersion(baseId);if(!base)throw new Error("Email campaign not found.");requireEmailRowTenant(sessionTenant,base,"create email campaign version");const {id:_,emailCampaignItemId:__,initiativeSlug:___,versionNumber:____,createdAt:_____,updatedAt:______,approvedAt:_______,...input}=base;void _;void __;void ___;void ____;void _____;void ______;void _______;const record=createEmailCampaignVersion(baseId,canonicalize(base.initiativeSlug,{...input,status:"draft"},tenantCtx));path(base.initiativeSlug);return record;}
export async function saveEmailCampaignVersionAction(id:string,input:EmailCampaignVersionInput){ const sessionTenant=await requireSessionTenant({action:"save email campaign version"}); const tenantCtx={sessionTenant,action:"save email campaign version"}; const current=getEmailCampaignVersion(id);if(!current)throw new Error("Email campaign not found.");requireEmailRowTenant(sessionTenant,current,"save email campaign version");const record=updateEmailCampaignVersion(id,canonicalize(current.initiativeSlug,input,tenantCtx));path(current.initiativeSlug);return record;}
