"use server";
import { revalidatePath } from "next/cache";
import { getBrandVoiceGuideline } from "@/lib/brand-voice/repository";
import { getManagedCampaignById } from "@/lib/campaigns/repository";
import { getContentVersion } from "@/lib/content-workspace/repository";
import { createEmailCampaignItem,createEmailCampaignVersion,getEmailCampaignVersion,updateEmailCampaignVersion } from "@/lib/email-campaigns/repository";
import { computeEmailStepClaimFindings,createSeededEmailCampaignInput,validateEmailCampaignInput } from "@/lib/email-campaigns/service";
import type { EmailCampaignVersionInput } from "@/lib/email-campaigns/types";
import { getInitiativeBySlug } from "@/lib/initiatives/repository";

function path(slug:string){revalidatePath(`/initiatives/${slug}`);revalidatePath(`/initiatives/${slug}/email-campaigns`);}
function canonicalize(slug:string,input:EmailCampaignVersionInput){const initiative=getInitiativeBySlug(slug);if(!initiative)throw new Error("Initiative not found.");const campaign=getManagedCampaignById(input.campaignId);if(!campaign||campaign.initiativeSlug!==slug)throw new Error("Campaign must belong to the same initiative.");const eligible=new Set<string>(),voices=new Set<string>();const steps=input.steps.map((step)=>{const source=getContentVersion(step.sourceContentVersionId);if(!source||source.initiativeSlug!==slug||!["approved","superseded"].includes(source.status))throw new Error("Source content must be approved or superseded in the same initiative.");const voice=getBrandVoiceGuideline(source.brandVoiceGuidelineId);if(!voice||voice.initiativeSlug!==slug||!["approved","superseded"].includes(voice.status))throw new Error("Pinned brand voice must be approved or superseded in the same initiative.");eligible.add(source.id);voices.add(voice.id);const canonical={...step,sourceContentUpdatedAt:source.updatedAt,sourceContentTitle:source.title,sourceMaterials:source.sourceMaterials,brandVoiceGuidelineId:voice.id,brandVoiceSnapshot:source.brandVoiceSnapshot};return{...canonical,claimFindings:computeEmailStepClaimFindings(initiative,canonical,voice)};});return validateEmailCampaignInput({...input,campaignName:campaign.name,steps},{campaignIds:new Set([campaign.id]),eligibleContentVersionIds:eligible,brandVoiceGuidelineIds:voices});}
export async function createEmailCampaignAction(slug:string,sourceId:string,campaignId:string){const source=getContentVersion(sourceId),campaign=getManagedCampaignById(campaignId);if(!source||source.initiativeSlug!==slug||!["approved","superseded"].includes(source.status))throw new Error("Select approved or superseded source content from this initiative.");if(!campaign||campaign.initiativeSlug!==slug)throw new Error("Select a campaign from this initiative.");const record=createEmailCampaignItem(slug,canonicalize(slug,createSeededEmailCampaignInput(source,campaign)));path(slug);return record;}
export async function createEmailCampaignVersionAction(baseId:string){const base=getEmailCampaignVersion(baseId);if(!base)throw new Error("Email campaign not found.");const {id:_,emailCampaignItemId:__,initiativeSlug:___,versionNumber:____,createdAt:_____,updatedAt:______,approvedAt:_______,...input}=base;void _;void __;void ___;void ____;void _____;void ______;void _______;const record=createEmailCampaignVersion(baseId,canonicalize(base.initiativeSlug,{...input,status:"draft"}));path(base.initiativeSlug);return record;}
export async function saveEmailCampaignVersionAction(id:string,input:EmailCampaignVersionInput){const current=getEmailCampaignVersion(id);if(!current)throw new Error("Email campaign not found.");const record=updateEmailCampaignVersion(id,canonicalize(current.initiativeSlug,input));path(current.initiativeSlug);return record;}
