"use server";
import { requireSessionTenant } from "@/lib/auth/session";

import { revalidatePath } from "next/cache";
import { getCampaignsByInitiativeSlug } from "@/lib/campaigns";
import { getBrandVoiceGuideline, listApprovedBrandVoiceVersions, isRowVisibleToTenant as isBrandVoiceRowVisible, requireRowTenantMatch as requireBrandVoiceRowTenant } from "@/lib/brand-voice/repository";
import { buildBrandVoiceContext } from "@/lib/brand-voice/service";
import { getContentVersion, listContentVersions, isRowVisibleToTenant as isContentRowVisible, requireRowTenantMatch as requireContentRowTenant } from "@/lib/content-workspace/repository";
import { getInitiativeBySlug, requireRowTenantMatch as requireInitiativeRowTenant } from "@/lib/initiatives/repository";
import { createVideoScriptItem, createVideoScriptVersion, getVideoScriptVersion, updateVideoScriptVersion, requireRowTenantMatch as requireVideoScriptRowTenant } from "@/lib/video-scripts/repository";
import { computeVideoScriptClaimFindings, createSeededVideoScriptInput, validateVideoScriptInput } from "@/lib/video-scripts/service";
import type { VideoScriptVersionInput } from "@/lib/video-scripts/types";

function paths(slug:string){ revalidatePath(`/initiatives/${slug}`); revalidatePath(`/initiatives/${slug}/video-scripts`); }
function context(slug:string,tenantCtx?:{sessionTenant:string;action:string}){ return { initiativeSlug:slug, eligibleContentVersionIds:new Set(listContentVersions(slug).filter((item)=>["approved","superseded"].includes(item.status)).filter((item)=>!tenantCtx||isContentRowVisible(tenantCtx.sessionTenant,item)).map((item)=>item.id)), campaignIds:new Set(getCampaignsByInitiativeSlug(slug).filter((item)=>!tenantCtx||isContentRowVisible(tenantCtx.sessionTenant,item)).map((item)=>item.id)), brandVoiceGuidelineIds:new Set(listApprovedBrandVoiceVersions(slug,true).filter((item)=>!tenantCtx||isBrandVoiceRowVisible(tenantCtx.sessionTenant,item)).map((item)=>item.id)) }; }
function derived(input:VideoScriptVersionInput,slug:string,tenantCtx?:{sessionTenant:string;action:string}){
  const initiative=getInitiativeBySlug(slug); if(!initiative) throw new Error("Initiative not found or inactive."); if(tenantCtx)requireInitiativeRowTenant(tenantCtx.sessionTenant,initiative,tenantCtx.action);
  const source=getContentVersion(input.sourceContentVersionId); if(!source||source.initiativeSlug!==slug||!["approved","superseded"].includes(source.status)) throw new Error("Source content must be an approved or superseded version from the same initiative."); if(tenantCtx)requireContentRowTenant(tenantCtx.sessionTenant,source,tenantCtx.action);
  const voice=getBrandVoiceGuideline(input.brandVoiceGuidelineId); if(!voice||voice.initiativeSlug!==slug||!["approved","superseded"].includes(voice.status)) throw new Error("Brand voice must be an approved version from the same initiative."); if(tenantCtx)requireBrandVoiceRowTenant(tenantCtx.sessionTenant,voice,tenantCtx.action);
  const serverInput={...input,sourceContentUpdatedAt:source.updatedAt,sourceContentTitle:source.title,sourceContentBody:source.body,sourceMaterials:source.sourceMaterials,brandVoiceSnapshot:buildBrandVoiceContext(voice)};
  return {...serverInput,claimFindings:computeVideoScriptClaimFindings(initiative,serverInput,voice)};
}
export async function createVideoScriptAction(sourceContentVersionId:string){ const sessionTenant=await requireSessionTenant({action:"create video script"}); const tenantCtx={sessionTenant,action:"create video script"}; const source=getContentVersion(sourceContentVersionId); if(!source) throw new Error("Source content not found."); requireContentRowTenant(sessionTenant,source,"create video script"); const input=derived(createSeededVideoScriptInput(source),source.initiativeSlug,tenantCtx); const created=createVideoScriptItem(source.initiativeSlug,validateVideoScriptInput(input,context(source.initiativeSlug,tenantCtx))); paths(source.initiativeSlug); return created; }
export async function createVideoScriptVersionAction(baseId:string){ const sessionTenant=await requireSessionTenant({action:"create video script version"}); const tenantCtx={sessionTenant,action:"create video script version"}; const base=getVideoScriptVersion(baseId); if(!base) throw new Error("Base video script not found."); requireVideoScriptRowTenant(sessionTenant,base,"create video script version"); const input=derived({...base,status:"draft",origin:"operator-edited",claimFindings:[],notes:`Created from video script version ${base.versionNumber}.`},base.initiativeSlug,tenantCtx); const created=createVideoScriptVersion(baseId,validateVideoScriptInput(input,context(base.initiativeSlug,tenantCtx))); paths(base.initiativeSlug); return created; }
export async function saveVideoScriptVersionAction(id:string,input:VideoScriptVersionInput){ const sessionTenant=await requireSessionTenant({action:"save video script version"}); const tenantCtx={sessionTenant,action:"save video script version"}; const current=getVideoScriptVersion(id); if(!current) throw new Error("Video script not found."); requireVideoScriptRowTenant(sessionTenant,current,"save video script version"); if(input.sourceContentVersionId!==current.sourceContentVersionId) throw new Error("Create a separate script to use different source content."); const validated=validateVideoScriptInput(derived({...input,origin:"operator-edited"},current.initiativeSlug,tenantCtx),context(current.initiativeSlug,tenantCtx)); const saved=updateVideoScriptVersion(id,validated); paths(current.initiativeSlug); return saved; }
